---
name: CD

on: 
  workflow_dispatch:
  push:
    branches:
      - main

env:
  ACR_NAME: ${{ secrets.ACR_NAME }}            
  WEBAPP_NAME: ${{ secrets.WEBAPP_NAME }}       
jobs:
  build:
    uses: ./.github/workflows/ci.yaml@main

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure CLI
        uses: Azure/login@v2.2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Docker image
        run: docker build -t restaurant-recommender:${{ github.sha }} .

      - name: Tag Docker image
        run: docker tag restaurant-recommender:${{ github.sha }} ${{ env.ACR_NAME }}.azurecr.io/restaurant-recommender:${{ github.sha }}

      - name: Login to Azure Container Registry
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Push Docker image
        run: docker push ${{ env.ACR_NAME }}.azurecr.io/restaurant-recommender:${{ github.sha }}

      - name: Deploy to Azure Web App
        uses: Azure/webapps-deploy@v3.0.1
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          images: ${{ env.ACR_NAME }}.azurecr.io/restaurant-recommender:${{ github.sha }}


  

